name: stylo_app
description: A Flutter E-Commerce Application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # =========================
  # State Management
  # =========================
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # =========================
  # Networking
  # =========================
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  internet_connection_checker_plus: ^2.7.2

  # =========================
  # Dependency Injection
  # =========================
  get_it: ^8.2.0

  # =========================
  # Navigation
  # =========================
  go_router: ^16.2.1

  # =========================
  # Local Storage
  # =========================
  shared_preferences: ^2.5.3

  # =========================
  # Responsive UI
  # =========================
  flutter_screenutil: ^5.9.3

  # =========================
  # UI
  # =========================
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.3.2
  intl: ^0.20.2

  # =========================
  # Image Picker
  # =========================
  image_picker: ^1.2.0

  # =========================
  # Icons
  # =========================
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/svg/
